"""
Typed contracts used by presentation agent tools.

The models intentionally stay light so we can iterate on the API surface
without dragging in implementation details too early.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, root_validator


class PresentationOutlineRequest(BaseModel):
    """Inputs required to plan a presentation outline."""

    topic: str = Field(..., description="Subject or theme for the presentation.")
    audience: str = Field(
        default="general",
        description="Intended audience persona (e.g., executives, engineers).",
    )
    desired_outcome: Optional[str] = Field(
        default=None, description="Desired impact or call to action for the audience."
    )
    slide_count_hint: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional target number of slides to shape the outline.",
    )
    include_appendix: bool = Field(
        default=False,
        description="Whether to reserve space for appendix materials.",
    )
    artifacts: List["OutlineArtifact"] = Field(
        default_factory=list,
        description="Context artifacts (e.g., narrative.md) that inform the story.",
    )


class OutlineSection(BaseModel):
    """One section of a presentation outline."""

    title: str
    key_points: List[str] = Field(default_factory=list)
    suggested_visuals: List[str] = Field(
        default_factory=list, description="Ideas for charts, images, or demos."
    )


class SlideOutline(BaseModel):
    """Per-slide blueprint emitted by the outline planner."""

    slide_id: str = Field(..., description="Stable identifier for the slide (e.g., S01).")
    title: str = Field(..., description="Conclusion-led headline for the slide.")
    message: Optional[str] = Field(
        default=None,
        description="Expanded interpretation or explanation of the claim.",
    )
    expected_evidence: List[str] = Field(
        default_factory=list,
        description="Evidence types the slide should contain (chart, table, quote, KPI…).",
    )
    notes: Optional[str] = Field(
        default=None,
        description="Execution guidance for evidence binding or drafting.",
    )
    layout: Optional[str] = Field(
        default=None,
        description="Optional layout style to influence the slide design. E.g., 'Single chart', 'Single Chart + Bullets', 'Title only', 'Two column text', 'Image with caption'.",
    )


class PresentationOutlineResponse(BaseModel):
    """Structured outline that downstream tools can expand into slides."""

    slides: List[SlideOutline] = Field(
        default_factory=list,
        description="Slide-level blueprints aligned to the narrative beats.",
    )

class SlideArtifact(BaseModel):
    """Artifact generated during insight analysis to support slide drafting."""

    name: str
    path: Optional[str] = Field(
        default=None,
        description="Absolute path or URI to the artifact (image/chart/table).",
    )
    description: Optional[str] = Field(default=None, description="How the artifact should be used.")
    artifact_type: Optional[str] = Field(
        default=None,
        description="Optional hint about artifact type (chart, table, note, kpi, image).",
    )
    is_primary: bool = Field(
        default=False,
        description="Whether this artifact should anchor the slide visual.",
    )


class SlideDraftRequest(BaseModel):
    """Describe a slide draft we want to produce."""

    slide_title: str
    key_points: List[str] = Field(default_factory=list)
    tone: Literal["formal", "casual", "story", "technical"] = "formal"
    include_speaker_notes: bool = True
    design_style: Optional[str] = Field(
        default=None,
        description="Optional hints about the desired design system or brand voice.",
    )
    artifacts: List[SlideArtifact] = Field(
        default_factory=list,
        description="Artifacts generated by insight analysis to bind into the slide.",
    )
    slide_identifier: Optional[str] = Field(
        default=None,
        description="Optional slide id/index for naming artifacts (e.g., S05).",
    )

    @root_validator(pre=True)
    def _ensure_defaults(cls, values: dict) -> dict:
        values.setdefault("key_points", [])
        values.setdefault("artifacts", [])
        return values


class SlideDraft(BaseModel):
    """Slide-level content container."""

    title: str
    bullets: List[str] = Field(default_factory=list)
    speaker_notes: Optional[str] = None
    suggested_visual: Optional[str] = None


class SlideDraftResponse(BaseModel):
    """Response payload for slide drafting tool calls."""

    slide: SlideDraft
    rationale: Optional[str] = Field(
        default=None, description="Explanation or reasoning for the drafted slide."
    )
    needs_followup: bool = Field(
        default=False,
        description="True when remaining insight content should spill into a subsequent slide.",
    )
    followup_hint: Optional[str] = Field(
        default=None,
        description="Guidance for drafting the next slide when needs_followup is True.",
    )
    ppt_artifact_path: Optional[str] = Field(
        default=None,
        description="Path/URI of the generated PPTX slide artifact.",
    )


class LayoutRegion(BaseModel):
    """Normalized bounding box for a layout region on the slide canvas."""

    x: float = Field(..., ge=0.0, le=1.0)
    y: float = Field(..., ge=0.0, le=1.0)
    w: float = Field(..., ge=0.0, le=1.0)
    h: float = Field(..., ge=0.0, le=1.0)


class LayoutSpecification(BaseModel):
    """Structured layout plan emitted by the layout agent."""

    slide_id: str
    intent: str
    layout_type: str
    theme: Optional[str] = Field(default=None, description="Brand or theme identifier.")
    regions: Dict[str, LayoutRegion] = Field(
        default_factory=dict,
        description="Named regions mapped to normalized coordinates.",
    )
    callout_anchors: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Anchors used when positioning annotations or callouts.",
    )
    constraints: Dict[str, Any] = Field(
        default_factory=dict,
        description="Layout constraints such as max bullets, character limits, or accessibility requirements.",
    )


class SlideQAReport(BaseModel):
    """Result from a slide formatting QA iteration."""

    status: Literal["PASS", "NEEDS_FIX"]
    score: int = Field(
        default=None,
        ge=0,
        le=100,
        description="Optional quality score from 0-100 reflecting slide quality.",
    )
    issues: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of issues detected during QA.",
    )
    patch: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Patch instructions the renderer should apply to resolve issues.",
    )
    notes: Optional[str] = Field(
        default=None,
        description="Optional free-form notes provided by the QA agent.",
    )


class GenerateSlideRequest(BaseModel):
    """Bundle insight and drafting instructions for the full slide pipeline."""
    thread_id: str = Field(..., description="Shared sandbox session identifier.")

    insight: InsightGenerationRequest = Field(
        ..., description="Insight generation inputs capturing data assets and analytical goals."
    )
    slide_outline: SlideOutline = Field(
        ..., description="Slide outline blueprint."
    )
    # draft: SlideDraftRequest = Field(
    #     ..., description="Slide drafting preferences including tone and prior artifacts."
    # )
    # max_qa_cycles: int = Field(
    #     default=3,
    #     ge=1,
    #     le=5,
    #     description="Maximum QA passes to run before accepting the slide formatting.",
    # )


class GenerateSlideResponse(BaseModel):
    """Aggregated result of the slide generation workflow."""

    insight: InsightGenerationResponse = Field(
        ..., description="Outputs from the insight generation stage."
    )
    layout: LayoutSpecification = Field(
        ..., description="Chosen layout specification for the slide."
    )
    draft: SlideDraftResponse = Field(
        ..., description="Final slide draft (copy + PPT metadata)."
    )
    qa_reports: List[SlideQAReport] = Field(
        default_factory=list, description="Ordered QA iteration reports."
    )
    render_artifact: Optional[SlideArtifact] = Field(
        default=None,
        description="Metadata for the rendered slide image artifact.",
    )


class PresentationAssemblyRequest(BaseModel):
    """Bundle slides into a deliverable artifact."""
    title: Optional[str] = Field(
        default=None,
        description="Optional presentation title",
    )
    thread_id: str = Field(
        default=None,
        description="Upstream conversation thread identifier for logging/artifacts.",
    )


class PresentationAssemblyResponse(BaseModel):
    """Minimal artifact handle for the assembled presentation."""

    artifact_path: str = Field(
        ...,
        description="URI or relative path where the assembled deck lives.",
    )
    preview_snippet: Optional[str] = Field(
        default=None,
        description="Short preview of the final artifact (e.g., link or excerpt).",
    )
    slide_count: Optional[int] = Field(
        default=None, description="Number of slides bundled into the artifact."
    )


class DataAsset(BaseModel):
    """Reference to a dataset or artifact that the sandbox can ingest."""

    name: str = Field(..., description="Human friendly name for the asset.")
    path: str = Field(..., description="Absolute path or s3:// URI to the asset.")
    description: Optional[str] = Field(
        default=None, description="Context that should influence the analysis."
    )
    size: Optional[int] = Field(
        default=None, description="Optional size metadata to seed the CEL log."
    )
    version_id: Optional[str] = Field(
        default=None,
        description="Optional object version for deterministic downloads.",
    )


class InsightGenerationRequest(BaseModel):
    """
    Inputs for statistical/visual storytelling aimed at slide-ready outputs.
    """
    task: str = Field(..., description="High-level goal for the statistical insight.")
    data_assets: List[DataAsset] = Field(
        default_factory=list,
        description="Datasets or tables to analyse. Supply s3:// URIs when remote.",
    )
    research_context: List[DataAsset] = Field(
        default_factory=list,
        description="Narrative or research context to seed the analysis. Supply s3:// URIs.",
    )


class InsightGenerationResponse(BaseModel):
    """Outputs from a statistical insight run."""

    ok: bool
    summary: str = Field(
        ..., description="LLM-evaluated summary tailored for slide narratives."
    )
    stdout: str = Field(default="", description="Raw stdout from the sandbox run.")
    stderr: str = Field(default="", description="Raw stderr from the sandbox run.")
    artifacts: List[dict] = Field(
        default_factory=list,
        description="Artifacts captured from outputs/ (charts, tables, notes).",
    )
    code_reference: Optional[str] = Field(
        default=None,
        description="Path or URI for the executed Python cell for auditing.",
    )


class OutlineArtifact(BaseModel):
    """Narrative or research artifact to guide outline planning."""

    name: str = Field(..., description="Artifact identifier (e.g., narrative.md).")
    path: Optional[str] = Field(
        default=None, description="Optional path/URI so the planner can reference provenance."
    )
    summary: Optional[str] = Field(
        default=None,
        description="Short summary of the artifact's content.",
    )
    content: Optional[str] = Field(
        default=None,
        description="Inline text excerpt to seed the planner (truncated upstream if large).",
    )


class PresentationWorkflowRequest(BaseModel):
    """End-to-end presentation workflow input."""

    thread_id: str = Field(..., description="Shared sandbox session identifier.")
    topic: str = Field(..., description="Presentation topic or narrative brief.")
    audience: str = Field(
        default="general",
        description="Intended audience persona (e.g., executives, engineers).",
    )
    desired_outcome: Optional[str] = Field(
        default=None,
        description="Desired impact or call to action for the audience.",
    )
    research_context: Optional[str] = Field(
        default=None,
        description="Qualitative findings to seed insights and slide copy.",
    )
    slide_count_hint: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional target number of slides to influence planning.",
    )
    include_appendix: bool = Field(
        default=False,
        description="Reserve appendix space when True.",
    )
    data_assets: List[DataAsset] = Field(
        default_factory=list,
        description="Structured datasets to analyse (S3 paths preferred).",
    )
    outline_artifacts: List[OutlineArtifact] = Field(
        default_factory=list,
        description="Narrative artifacts to seed outline planning.",
    )
    max_iterations: Optional[int] = Field(
        default=1,
        description="Maximum LangGraph passes through evidence/drafting loop.",
    )


class PresentationWorkflowResponse(BaseModel):
    """Aggregated output of the presentation workflow."""

    thread_id: str
    outline: PresentationOutlineResponse
    slide_drafts: Dict[str, SlideDraftResponse]
    deck: Optional[PresentationAssemblyResponse] = None
    insights: Dict[str, dict] = Field(default_factory=dict)


PresentationOutlineRequest.model_rebuild()
